alter table t_msg_mp_template
    add preview_user text;
alter table t_msg_mp_template
    add wx_account_id int;
alter table t_msg_kefu
    add preview_user text;
alter table t_msg_kefu
    add wx_account_id int;
alter table t_msg_kefu_priority
    add preview_user text;
alter table t_msg_kefu_priority
    add wx_account_id int;
alter table t_msg_ma_subscribe
    add preview_user text;
alter table t_msg_ma_subscribe
    add wx_account_id int;
alter table t_msg_ma_template
    add preview_user text;
alter table t_msg_ma_template
    add wx_account_id int;
alter table t_msg_wx_uniform
    add preview_user text;
alter table t_msg_wx_uniform
    add wx_account_id int;
alter table t_msg_ding
    add preview_user text;
alter table t_msg_http
    add preview_user text;
alter table t_msg_mail
    add preview_user text;
alter table t_msg_sms
    add preview_user text;
alter table t_msg_wx_cp
    add preview_user text;
