<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fangxuele.wepush.next</groupId>
        <artifactId>wepush-next-parent</artifactId>
        <version>1.1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>provider-carrier-common</artifactId>
    <name>WePush Next :: Carrier SMS Provider Common</name>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>provider-spi</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.chinamobile.cmos</groupId>
            <artifactId>sms-client</artifactId>
            <version>${sms-client.version}</version>
            <exclusions>
                <exclusion><groupId>com.chinamobile.cmos</groupId><artifactId>wbxml-stream</artifactId></exclusion>
                <exclusion><groupId>com.sleepycat</groupId><artifactId>je</artifactId></exclusion>
                <exclusion><groupId>de.ruedigermoeller</groupId><artifactId>fst</artifactId></exclusion>
                <exclusion><groupId>io.netty</groupId><artifactId>netty-all</artifactId></exclusion>
                <exclusion><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId></exclusion>
            </exclusions>
        </dependency>
        <dependency><groupId>com.google.guava</groupId><artifactId>guava</artifactId><version>${guava.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-common</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-buffer</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-codec</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-codec-haproxy</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-codec-socks</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-codec-http</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-handler</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-handler-proxy</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-resolver</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-transport</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-transport-native-unix-common</artifactId><version>${netty.version}</version></dependency>
        <dependency><groupId>io.netty</groupId><artifactId>netty-transport-classes-epoll</artifactId><version>${netty.version}</version></dependency>
        <dependency>
            <groupId>org.apache.commons</groupId><artifactId>commons-pool2</artifactId>
            <version>${commons-pool2.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-beanutils</groupId><artifactId>commons-beanutils</artifactId>
            <version>${commons-beanutils.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId><artifactId>commons-codec</artifactId>
            <version>${commons-codec.version}</version>
        </dependency>
        <dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId><scope>provided</scope></dependency>
        <dependency><groupId>org.slf4j</groupId><artifactId>slf4j-simple</artifactId><scope>test</scope></dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope>
        </dependency>
    </dependencies>
</project>
